services:
  - type: web
    plan: standard
    runtime: image
    name: n8n-service
    region: frankfurt
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      - key: N8N_ENCRYPTION_KEY
        value: change-this-encryption-key

      # Supabase database config
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: db.nbhuimqlxwcgfmjzlsve.supabase.co
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_USER
        value: postgres
      - key: DB_POSTGRESDB_PASSWORD
        value: CGnPktEKuultxzuX
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"

      # n8n Web config
      - key: WEBHOOK_URL
        value: "https://n8n.nodestacks.com"
      - key: N8N_HOST
        value: "n8n.nodestacks.com"
      - key: N8N_PORT
        value: "5678"
