services:
  - type: web
    plan: standard
    runtime: image
    name: n8n-service
    region: frankfurt
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      # Encryptie
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      # Supabase database config
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: db.nbhuimqlxwcgfmjzlsve.supabase.co
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_USER
        value: postgres
      - key: DB_POSTGRESDB_PASSWORD
        value: CGnPktEKuultxzuX
      - key: DB_POSTGRESDB_SCHEMA
        value: public
      - key: DB_POSTGRESDB_SSL_ENABLED
        value: "true"
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"

      # Optioneel: voor betrouwbaardere connectie & debug
      - key: DB_POSTGRESDB_POOL_SIZE
        value: "5"
      - key: DB_POSTGRESDB_CONNECTION_TIMEOUT
        value: "20000"
      - key: DB_POSTGRESDB_IDLE_CONNECTION_TIMEOUT
        value: "30000"

      # Fallback naar SQLite blokkeren
      - key: DB_SQLITE_DATABASE
        value: "/dev/null"

      # Logging (voor debug)
      - key: DB_LOGGING
        value: "true"
      - key: DB_LOG_OUTPUT
        value: "all"
      - key: DB_LOGGING_ENABLED
        value: "true"

      # n8n Web config
      - key: WEBHOOK_URL
        value: https://n8n.nodestacks.com
      - key: N8N_HOST
        value: n8n.nodestacks.com
      - key: N8N_PORT
        value: "5678"

      # Omgevingsinstelling
      - key: NODE_ENV
        value: production
