services:
  - type: web
    name: n8n-service
    plan: standard
    region: frankfurt
    runtime: image
    image:
      url: docker.io/n8nio/n8n:latest
    envVars:
      - fromGroup: n8n-evn-var
      - key: GENERIC_TIMEZONE
        value: Europe/Amsterdam

  - type: worker
    name: n8n-runner
    plan: standard
    region: frankfurt
    runtime: image
    image:
      url: docker.io/n8nio/n8n:latest
    envVars:
      - fromGroup: n8n-evn-var
      - key: GENERIC_TIMEZONE
        value: Europe/Amsterdam
