services:
  - type: web
    plan: standard
    runtime: image
    name: n8n-service
    region: frankfurt
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      # Algemene settings
      - key: GENERIC_TIMEZONE
        value: Europe/Amsterdam
      - key: N8N_ENCRYPTION_KEY
        value: test
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
      - key: N8N_RUNNERS_ENABLED
        value: "true"

      # Database settings
      - key: DB_TYPE
        value: test
      - key: DB_POSTGRESDB_HOST
        value: test
      - key: DB_POSTGRESDB_PORT
        value: test
      - key: DB_POSTGRESDB_DATABASE
        value: test
      - key: DB_POSTGRESDB_USER
        value: test
      - key: DB_POSTGRESDB_PASSWORD
        value: test
      - key: DB_POSTGRESDB_SCHEMA
        value: test

      # Webconfig alleen voor web-service
      - key: N8N_HOST
        value: test
      - key: N8N_PORT
        value: test
      - key: WEBHOOK_URL
        value: test

  - type: worker
    plan: standard
    name: n8n-runner
    region: frankfurt
    runtime: image
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      - key: GENERIC_TIMEZONE
        value: Europe/Amsterdam
      - key: N8N_ENCRYPTION_KEY
        value: test
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
      - key: N8N_RUNNERS_ENABLED
        value: "true"
      
      # Database settings
      - key: DB_TYPE
        value: test
      - key: DB_POSTGRESDB_HOST
        value: test
      - key: DB_POSTGRESDB_PORT
        value: test
      - key: DB_POSTGRESDB_DATABASE
        value: test
      - key: DB_POSTGRESDB_USER
        value: test
      - key: DB_POSTGRESDB_PASSWORD
        value: test
      - key: DB_POSTGRESDB_SCHEMA
        value: test
