services:
  - type: web
    plan: standard
    runtime: image
    name: n8n-service
    region: frankfurt
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      # Encryptie
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      # Supabase database config
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: supabase-host
      - key: DB_POSTGRESDB_PORT
        value: supabase-port
      - key: DB_POSTGRESDB_DATABASE
        value: supabase-name
      - key: DB_POSTGRESDB_USER
        value: supabase-user
      - key: DB_POSTGRESDB_PASSWORD
        value: supabase-password
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"

      # Fallback naar SQLite blokkeren
      - key: DB_SQLITE_DATABASE
        value: "/dev/null"

      # Logging (voor debug)
      - key: DB_LOGGING
        value: "true"
      - key: DB_LOG_OUTPUT
        value: "all"
      - key: DB_LOGGING_ENABLED
        value: "true"

      # n8n Web config
      - key: WEBHOOK_URL
        fromSecret: webhook-url
      - key: N8N_HOST
        fromSecret: n8n-host
      - key: N8N_PORT
        fromSecret: n8n-port

      # Omgevingsinstelling
      - key: NODE_ENV
        value: production
