services:
  - type: web
    plan: standard
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      # Supabase database config via secrets
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromSecret: supabase-host
      - key: DB_POSTGRESDB_PORT
        fromSecret: supabase-port
      - key: DB_POSTGRESDB_DATABASE
        fromSecret: supabase-name
      - key: DB_POSTGRESDB_USER
        fromSecret: supabase-user
      - key: DB_POSTGRESDB_PASSWORD
        fromSecret: supabase-password
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"

      # n8n Web config
      - key: WEBHOOK_URL
        fromSecret: webhook-url
      - key: N8N_HOST
        fromSecret: n8n-host
      - key: N8N_PORT
        fromSecret: n8n-port
