services:
  - type: web
    plan: standard
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      - key: N8N_ENCRYPTION_KEY

      # Supabase database config (verplicht in de UI in te vullen)
      - key: DB_TYPE
      - key: DB_POSTGRESDB_HOST
      - key: DB_POSTGRESDB_PORT
      - key: DB_POSTGRESDB_DATABASE
      - key: DB_POSTGRESDB_USER
      - key: DB_POSTGRESDB_PASSWORD
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED

      # n8n Web config
      - key: WEBHOOK_URL
      - key: N8N_HOST
      - key: N8N_PORT
