services:
  - type: web
    plan: standard
    runtime: image
    name: n8n-service
    region: frankfurt
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: DB_LOGGING
        value: "true"
      - key: NODE_ENV
        value: production
